# Generated by Django 2.2.14 on 2023-12-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gritmakerApp', '0002_auto_20231203_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='timestamp',
        ),
    ]
