# Generated by Django 2.2.14 on 2023-12-08 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gritmakerApp', '0003_remove_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
