# Generated by Django 2.2.14 on 2023-12-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gritmakerApp', '0004_sensordata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='timestamp',
        ),
    ]
