# Generated by Django 2.2.14 on 2023-12-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gritmakerApp', '0006_sensordata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
