# Generated by Django 2.2.14 on 2023-12-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gritmakerApp', '0007_auto_20231207_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
