# Generated by Django 2.2.14 on 2023-12-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gritmakerApp', '0008_auto_20231207_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
